### ISSUE TITLE
chain latency about the first and last node can not be display

### ISSUE THREAD

**Issue by HaochunLiang** [tier4/caret#201] opened 2024-08-12 07:08 UTC
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [X] I've read [document](https://tier4.github.io/CARET_doc/main/) and no solution were found.

### Issue type

Bug

### Step where the issue is related to

Visualization

### Environments

OS: Ubuntu 22.04.1 LTS
Kernel version: 6.5.0-44-generic
ROS 2: Humble
CPU: Intel(R) i5-14600k
Memory: 48.0 GiB

### CARET version

CARET: v0.5.9
CARET_analyze: 3655d76afcf8e58d58c060bccc78f8b0949e0372
CARET_trace: 5d777a34d5d30e18a66a345566f9441bfa24cd0f

### Description

When I want to print out the Chain latency, the latency information of the first and last nodes cannot be displayed.
<img width="257" alt="image" src="https://github.com/user-attachments/assets/896a55f1-dd0d-4f36-b31e-2f2a54d89d62">

### Steps to reproduce

from caret_analyze.plot import chain_latency
from caret_analyze import Application, Architecture, Lttng
from bokeh.plotting import output_notebook, figure, show
output_notebook()

arch = Architecture('yaml', '/path/to/architecture_file')
lttng = Lttng('/path/to/trace_data')
app = Application(arch, lttng)
path = app.get_path('target_path')

chain_latency(path, granularity='node', lstrip_s=1, rstrip_s=1)

**Comment by ymski** [comment] 2024-08-16 02:07
Hi @HaochunLiang . Thanks for asking the question.
By default, the latency of the nodes at the end of a path is not output, since the definition of paths in CARET does not allow for the natural definition of latency at the first and last nodes of a path. However, an option allows latency to be displayed for the first and last nodes as well.

The following is sample code for outputting latency at the end of a path.
```
from caret_analyze.plot import chain_latency
path = app.get_path('target_path')
path.include_first_callback = True
path.include_last_callback = True
chain_latency(path, granularity='node', lstrip_s=1, rstrip_s=1)
```

Result
![image](https://github.com/user-attachments/assets/46795969-e3aa-4c8c-9622-eae1cb0259b3)

Documentation on these options can be found [here](https://tier4.github.io/caret_doc/latest/configuration/inter_node_data_path/#considering-firstlast-callback).

Related links
- [Path Definition](https://tier4.github.io/caret_doc/latest/design/event_and_latency_definitions/path/)
- [Node Definition](https://tier4.github.io/caret_doc/latest/design/event_and_latency_definitions/node/)
- [Communication Definition](https://tier4.github.io/caret_doc/latest/design/event_and_latency_definitions/communication/)

**Comment by ymski** [comment] 2024-09-24 09:55
@HaochunLiang 
Since we have not received a response for a long time and the status of the issue is unknown, we are closing it.
If you encounter similar problems, please create another issue.

**Closed by ymski** 2024-09-24 09:55 UTC
Labels: bug
